---
title: "OpenStreetMap"
format: gfm
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(paged.print = FALSE)
options(digits = 5)
```

# Interrogating

```{r}
library(osmdata)
```

```{r}
available_features()
```

```{r}
available_tags(feature = "water")
```

```{r}
available_tags(feature = "amenity")
```

# Area of interest

## With a bounding box

```{r}
abq_bb <- matrix(
  data = c(-106.9, -106.4, 34.9, 35.3),
  nrow = 2, byrow = T
)
colnames(abq_bb) <- c("min", "max")
rownames(abq_bb) <- c("x", "y")
abq_bb
```


```{r}
abq_bb <- getbb("Albuquerque")
abq_bb
```

# Roads

```{r}
available_tags(feature = "highway")
```

```{r}
abq_major_roads <- abq_bb |>
  opq() |>
  add_osm_feature(
    key = "highway",
    value = c("motorway", "primary", "secondary")
  ) |>
  osmdata_sf()
abq_major_roads
```

```{r osm-tut-plot-1}
library(ggplot2)

street_plot <- ggplot() +
  geom_sf(
    data = abq_major_roads$osm_lines,
    inherit.aes = F,
    color = "black",
    size = 0.2
  )
street_plot
```

```{r}
abq_minor <- getbb("Albuquerque") |>
  opq() |>
  add_osm_feature(key = "highway", value = c("tertiary", "residential")) |>
  osmdata_sf()
```

```{r osm-tut-plot-2}
street_plot_minor <- street_plot +
  geom_sf(
    data = abq_minor$osm_lines,
    inherit.aes = F, color = "grey50", size = 0.1
  )
street_plot_minor
```

```{r osm-tut-plot-3}
abq_tert <- getbb("Albuquerque") |>
  opq() |>
  add_osm_feature(key = "highway", value = c("tertiary")) |>
  osmdata_sf()

street_plot_tert <- street_plot +
  geom_sf(data = abq_tert$osm_lines, inherit.aes = F, color = "grey50", size = 0.1)
street_plot_tert
```


```{r}
abq_rest <- abq_bb |>
  opq() |>
  add_osm_feature("amenity", "restaurant") |>
  osmdata_sf()
abq_rest
```



```{r}
# Query for Tucson restaurants, them filter to mexican cuisine
abq_rest_mex <- getbb(place_name = "Albuquerque") %>%
  opq() %>%
  add_osm_feature(key = "amenity", value = "restaurant") %>%
  add_osm_feature(key = "cuisine", value = "mexican") %>% # filters results
  osmdata_sf()
abq_rest_mex
```

```{r osm-tut-plot-4}
rest_plot <- street_plot_tert +
  geom_sf(
    data = abq_rest_mex$osm_points,
    inherit.aes = F,
    size = 1.5, color = "red"
  )

rest_plot
```

```{r osm-tut-plot-5}
rest_plot +
  coord_sf(
    xlim = c(-106.8, -106.55),
    ylim = c(35, 35.25)
  ) +
  theme_void()
```

```{r}
abq_rest_mex <- getbb(place_name = "Albuquerque") %>%
  opq() %>%
  add_osm_feature(key = "amenity", value = "restaurant") %>%
  add_osm_feature(key = "cuisine", value = "thai") %>% # filters results
  osmdata_sf()
abq_rest_mex
```

```{r}
abq_micro_brew <- getbb(place_name = "Albuquerque") %>%
  opq() %>%
  add_osm_feature(key = "microbrewery", value = "yes") |>
  osmdata_sf()
abq_micro_brew
```

```{r osm-tut-plot-7}
brew_plot <- street_plot_tert +
  geom_sf(
    data = abq_micro_brew$osm_points,
    inherit.aes = F,
    size = 1.5, color = "red"
  ) +
  coord_sf(
    xlim = c(-106.8, -106.55),
    ylim = c(35, 35.25)
  ) +
  theme_void()
brew_plot
```

```{r}
str(abq_micro_brew)
```

```{r}
abq_micro_brew$osm_points$name
```

```{r}
abq_bar_pub <- getbb(place_name = "Albuquerque") %>%
  opq() %>%
  add_osm_feature(key = "amenity", value = "bar") |>
  add_osm_feature(key = "drink:cocktail", value = "served") |>
  osmdata_sf()
abq_bar_pub
```



